name: hugo-deploy

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
          
#       - name: Hugo setup
#         uses: peaceiris/actions-hugo@v2.4.13
#         with:
#           hugo-version: '0.88.1'
#           extended: true
  
      - name: 'Building...'
        uses: reuixiy/hugo-deploy@v1
        env:
          DEPLOY_REPO: QIN2DIM/test-demo-repo
          DEPLOY_BRANCH: build
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
          TZ: Asia/Shanghai

